CREATE DATABASE burgers_db; 
USE burgers_db; 

CREATE TABLE burgers (
	ID INT NOT NULL AUTO_INCREMENT,
	BURGER_NAME VARCHAR(255) NOT NULL, 
	DEVOURED BOOLEAN DEFAULT false, 
	DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
); 